# Generated by Django 3.1.1 on 2020-11-05 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guradianparticulars',
            name='region',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
