# Generated by Django 3.1.1 on 2020-11-05 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_guradianparticulars_region'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='user',
            unique_together={('first_name', 'middle_name', 'last_name')},
        ),
    ]
