# Generated by Django 3.1.1 on 2020-11-05 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_auto_20201105_1529'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='tel_office',
            new_name='tel',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='tel_residence',
        ),
    ]
