# Generated by Django 3.1.1 on 2020-11-09 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_examtype'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_type', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='ExamType',
        ),
        migrations.AddField(
            model_name='exam',
            name='exam_file',
            field=models.FileField(default='', upload_to='exams'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='exam',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.examgroup'),
        ),
        migrations.AlterUniqueTogether(
            name='exam',
            unique_together={('subject', 'myclass', 'date', 'exam', 'exam_file')},
        ),
        migrations.RemoveField(
            model_name='exam',
            name='exam_type',
        ),
    ]
