# Generated by Django 3.1.1 on 2020-11-09 13:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_auto_20201109_1611'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exam',
            old_name='exam',
            new_name='exam_group',
        ),
        migrations.AddField(
            model_name='examgroup',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='examgroup',
            name='myclass',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='App.myclass'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='examgroup',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterUniqueTogether(
            name='exam',
            unique_together={('subject', 'date', 'exam_group', 'exam_file')},
        ),
        migrations.RemoveField(
            model_name='exam',
            name='myclass',
        ),
    ]
