# Generated by Django 3.1.1 on 2020-11-09 13:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_auto_20201109_1614'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examgroup',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='examgroup',
            name='exam_type',
        ),
        migrations.RemoveField(
            model_name='examgroup',
            name='start_date',
        ),
        migrations.CreateModel(
            name='ExamGroupMain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField(default=django.utils.timezone.now)),
                ('exam_type', models.CharField(max_length=20)),
            ],
            options={
                'unique_together': {('start_date', 'end_date', 'exam_type')},
            },
        ),
        migrations.AddField(
            model_name='examgroup',
            name='examgroupmain',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='App.examgroupmain'),
            preserve_default=False,
        ),
    ]
