# Generated by Django 3.1.1 on 2020-11-10 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0011_auto_20201110_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendation',
            name='tag',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='recommendation',
            unique_together={('pupil', 'term', 'tag', 'date')},
        ),
        migrations.RemoveField(
            model_name='recommendation',
            name='subject',
        ),
    ]
