# Generated by Django 3.1.1 on 2020-11-10 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0012_auto_20201110_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='for_emergency',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='for_payment',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
