# Generated by Django 3.1.1 on 2020-11-12 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0014_hierarchy'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hierarchy',
        ),
    ]
