# Generated by Django 3.1.1 on 2020-11-12 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0016_hierarchy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='previousschool',
            name='level',
        ),
    ]
