# Generated by Django 3.1.1 on 2020-11-12 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0018_auto_20201113_0129'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicalrecords',
            old_name='is_Eye_problems',
            new_name='is_eye_problems',
        ),
    ]
