# Generated by Django 3.1.1 on 2020-11-12 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0019_auto_20201113_0140'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GuradianParticulars',
            new_name='GuardianParticulars',
        ),
    ]
