# Generated by Django 3.1.1 on 2020-11-12 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0020_auto_20201113_0145'),
    ]

    operations = [
        migrations.AddField(
            model_name='guardianparticulars',
            name='district',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
