# Generated by Django 3.1.1 on 2020-11-12 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0021_guardianparticulars_district'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='tag',
            new_name='name',
        ),
    ]
