# Generated by Django 3.1.1 on 2020-11-13 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0023_contact_relation'),
    ]

    operations = [
        migrations.AddField(
            model_name='hierarchy',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
