# Generated by Django 3.1.1 on 2020-11-14 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0025_auto_20201113_1328'),
    ]

    operations = [
        migrations.RenameField(
            model_name='journal',
            old_name='cr_ledger',
            new_name='bal_acc_no',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='dr_ledger',
        ),
        migrations.AddField(
            model_name='journal',
            name='acc_no',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='acc_type', to='App.chartofaccounts'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='journal',
            name='acc_type',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='journal',
            name='bal_acc_type',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='journal',
            name='doc_type',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
