# Generated by Django 3.1.1 on 2020-11-16 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0028_auto_20201114_2332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journal',
            name='payer_payee',
        ),
    ]
