# Generated by Django 3.1.1 on 2020-11-16 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0029_remove_journal_payer_payee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='acc_type',
            field=models.CharField(blank=True, default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='journal',
            name='bal_acc_type',
            field=models.CharField(blank=True, default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='journal',
            name='description',
            field=models.CharField(max_length=100),
        ),
    ]
