# Generated by Django 3.1.1 on 2020-11-16 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0030_auto_20201116_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='acc_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trancs', to='App.chartofaccounts'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='bal_acc_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bal_trancs', to='App.chartofaccounts'),
        ),
    ]
