# Generated by Django 3.1.1 on 2020-11-16 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0031_auto_20201116_1108'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inv_no', models.CharField(max_length=10)),
                ('posting_date', models.DateField()),
                ('description', models.CharField(max_length=30)),
                ('amount', models.IntegerField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.pupil')),
            ],
        ),
    ]
