# Generated by Django 3.1.1 on 2020-11-16 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0032_invoice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='posting_date',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='cheque_no',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.chartofaccounts'),
        ),
        migrations.CreateModel(
            name='JournalExtras',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cheque_no', models.IntegerField(blank=True, null=True)),
                ('journal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='App.journal')),
            ],
            options={
                'verbose_name_plural': 'Journal Extras',
            },
        ),
    ]
