# Generated by Django 3.1.1 on 2020-11-16 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0033_auto_20201116_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='inv_no',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='journal',
            name='doc_no',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
