# Generated by Django 3.1.1 on 2020-11-16 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0034_auto_20201117_0044'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='is_posted',
            field=models.BooleanField(default=False),
        ),
    ]
