# Generated by Django 3.1.1 on 2020-11-16 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0036_auto_20201117_0145'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='start',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
