# Generated by Django 3.1.1 on 2020-11-16 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0037_customer_start'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
