# Generated by Django 3.1.1 on 2021-05-12 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0041_auto_20210512_0609'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StoreRecord',
            new_name='Store',
        ),
    ]
