# Generated by Django 3.1.1 on 2021-05-12 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0042_auto_20210512_0610'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Store',
            new_name='StoreRecord',
        ),
    ]
