# Generated by Django 3.1.1 on 2021-05-13 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0043_auto_20210512_0611'),
    ]

    operations = [
        migrations.AddField(
            model_name='storerecord',
            name='going_out',
            field=models.BooleanField(default=True),
        ),
    ]
