# Generated by Django 3.1.1 on 2021-05-13 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0044_storerecord_going_out'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storerecord',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.storeitem'),
        ),
    ]
