# Generated by Django 3.1.1 on 2021-05-13 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0045_auto_20210513_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeitem',
            name='qty',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
